import type { Metadata } from 'next';
import './globals.css';

import { primaryFont, secondaryFont } from '@/helpers/FontSettings';

import { TopBar } from '@/components/ui/TopBar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${primaryFont.variable} ${secondaryFont.variable} antialiased`}
			>
				<TopBar />
				{children}
			</body>
		</html>
	);
}
